version: '3.8'

services:
  docquery-web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
    
  docquery-api:
    build: .
    command: ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped