services:
  - type: web
    name: docquery-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0 --server.headless true
    envVars:
      - key: PYTHONUNBUFFERED
        value: true
      - key: STREAMLIT_SERVER_HEADLESS  
        value: true
      - key: STREAMLIT_BROWSER_GATHER_USAGE_STATS
        value: false